#!/bin/bash

echo "=== Ubuntu Docker Compose 已更新 ==="
echo ""
echo "当前版本:"
echo "Docker: 27.5.1 (最新)"
echo "Docker Compose: 2.33.0 (已更新到 V2 ✓)"
echo ""
echo "现在可以使用以下方式启动服务："
echo ""
echo "1. 安装 Docker Compose V2 (推荐):"
echo "----------------------------------------"
echo "# 安装 Docker Compose 插件"
echo "sudo apt-get update"
echo "sudo apt-get install docker-compose-plugin"
echo ""
echo "# 测试新版本"
echo "docker compose version"
echo ""
echo "# 使用新命令启动服务"
echo "docker compose -f docker-compose-dev.yml up -d api mcp"
echo ""
echo "2. 或者直接使用 Python 启动:"
echo "----------------------------------------"
echo "# 安装依赖"
echo "pip3 install -r requirements.txt"
echo ""
echo "# 启动 API 服务"
echo "cd server && python3 -m uvicorn api.flash_search_api:app --host 0.0.0.0 --port 8060 --reload &"
echo ""
echo "# 启动 MCP 服务"
echo "cd server && python3 mcp/mira_flash_search.py --transport sse --host 0.0.0.0 --port 9060 &"
echo ""
echo "3. 使用更新的管理脚本:"
echo "----------------------------------------"
echo "./manage-services-v2.sh start-python"
echo ""