#!/bin/bash

# xDAN RAG Copilot 本地启动脚本 - 支持持久化日志和结构化输出
# 简化的部署方式，适合本地开发和测试

# 基础配置
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="$PROJECT_ROOT/logs"
PID_DIR="$PROJECT_ROOT/.pids"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# 服务配置
BACKEND_PORT="${BACKEND_PORT:-8050}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"
RAGFLOW_API_URL="${RAGFLOW_API_URL:-http://150.109.16.195:7080}"
RAGFLOW_API_KEY="${RAGFLOW_API_KEY:-ragflow-g4ZWE3OTNhNDUxYTExZjA4MTljMDI0Mm}"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 创建必要的目录
mkdir -p "$LOG_DIR/backend" "$LOG_DIR/frontend" "$PID_DIR"

# 日志函数
log() {
    local level=$1
    local component=$2
    local message=$3
    local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
    local color=""
    
    case $level in
        "INFO") color=$BLUE ;;
        "SUCCESS") color=$GREEN ;;
        "WARNING") color=$YELLOW ;;
        "ERROR") color=$RED ;;
    esac
    
    # 输出到控制台
    echo -e "${color}[$timestamp] [$level] [$component] $message${NC}"
    
    # 输出到日志文件（无颜色）
    local component_lower=$(echo "$component" | tr '[:upper:]' '[:lower:]')
    echo "[$timestamp] [$level] [$component] $message" >> "$LOG_DIR/$component_lower/service_${TIMESTAMP}.log"
}

# 检查端口是否被占用
check_port() {
    local port=$1
    if lsof -Pi :$port -sTCP:LISTEN -t >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

# 停止服务
stop_service() {
    local service=$1
    local pid_file="$PID_DIR/${service}.pid"
    
    if [ -f "$pid_file" ]; then
        local pid=$(cat "$pid_file")
        if kill -0 $pid 2>/dev/null; then
            log "INFO" "$service" "停止服务 (PID: $pid)"
            kill $pid
            sleep 2
            if kill -0 $pid 2>/dev/null; then
                log "WARNING" "$service" "强制停止服务"
                kill -9 $pid
            fi
            rm -f "$pid_file"
            log "SUCCESS" "$service" "服务已停止"
        else
            log "INFO" "$service" "服务未运行"
            rm -f "$pid_file"
        fi
    else
        log "INFO" "$service" "未找到PID文件"
    fi
}

# 启动后端服务
start_backend() {
    log "INFO" "BACKEND" "准备启动后端服务..."
    
    # 检查端口
    if check_port $BACKEND_PORT; then
        log "ERROR" "BACKEND" "端口 $BACKEND_PORT 已被占用"
        return 1
    fi
    
    # 检查Python环境
    if [ ! -d "$PROJECT_ROOT/venv" ]; then
        log "INFO" "BACKEND" "创建Python虚拟环境..."
        python3 -m venv "$PROJECT_ROOT/venv"
    fi
    
    # 激活虚拟环境并安装依赖
    source "$PROJECT_ROOT/venv/bin/activate"
    
    # 检查并安装依赖
    log "INFO" "BACKEND" "检查Python依赖..."
    pip install -q fastapi uvicorn python-multipart requests pydantic
    
    # 创建环境配置文件
    cat > "$PROJECT_ROOT/.env" << EOF
# Auto-generated by local_start.sh
ENVIRONMENT=local
PORT=$BACKEND_PORT
HOST=0.0.0.0
LOG_LEVEL=info
RAGFLOW_API_URL=$RAGFLOW_API_URL
RAGFLOW_API_KEY=$RAGFLOW_API_KEY
EOF
    
    # 导出环境变量
    export PORT=$BACKEND_PORT
    
    # 启动后端服务
    log "INFO" "BACKEND" "启动后端服务 (端口: $BACKEND_PORT)"
    
    # 查找API服务器文件
    API_SERVER=""
    if [ -f "$PROJECT_ROOT/xdan_api_proxy_server_fixed.py" ]; then
        API_SERVER="$PROJECT_ROOT/xdan_api_proxy_server_fixed.py"
    elif [ -f "$PROJECT_ROOT/xdan_api_proxy_server.py" ]; then
        API_SERVER="$PROJECT_ROOT/xdan_api_proxy_server.py"
    else
        log "ERROR" "BACKEND" "未找到API服务器文件"
        return 1
    fi
    
    # 使用nohup启动，输出重定向到日志
    nohup env PORT=$BACKEND_PORT python "$API_SERVER" > "$LOG_DIR/backend/output_${TIMESTAMP}.log" 2>&1 &
    local pid=$!
    echo $pid > "$PID_DIR/backend.pid"
    
    # 等待服务启动
    sleep 3
    
    # 健康检查
    if curl -s -f "http://localhost:$BACKEND_PORT/health" > /dev/null 2>&1; then
        log "SUCCESS" "BACKEND" "后端服务启动成功 (PID: $pid)"
        log "INFO" "BACKEND" "API文档: http://localhost:$BACKEND_PORT/docs"
        return 0
    else
        log "ERROR" "BACKEND" "后端服务启动失败"
        stop_service "backend"
        return 1
    fi
}

# 启动前端服务
start_frontend() {
    log "INFO" "FRONTEND" "准备启动前端服务..."
    
    # 检查端口
    if check_port $FRONTEND_PORT; then
        log "ERROR" "FRONTEND" "端口 $FRONTEND_PORT 已被占用"
        return 1
    fi
    
    # 检查前端目录
    FRONTEND_DIR="$PROJECT_ROOT/frontend"
    if [ ! -d "$FRONTEND_DIR" ]; then
        log "WARNING" "FRONTEND" "前端目录不存在，创建示例前端应用..."
        mkdir -p "$FRONTEND_DIR"
        
        # 创建简单的前端应用
        cat > "$FRONTEND_DIR/index.html" << 'EOF'
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>xDAN RAG Copilot</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f5f5f5; }
        .container { max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .status { padding: 10px; margin: 10px 0; border-radius: 4px; }
        .status.success { background: #d4edda; color: #155724; }
        .status.error { background: #f8d7da; color: #721c24; }
        .api-test { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        button { padding: 10px 20px; background: #007bff; color: white; border: none; border-radius: 4px; cursor: pointer; }
        button:hover { background: #0056b3; }
        pre { background: #f4f4f4; padding: 10px; border-radius: 4px; overflow-x: auto; margin-top: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🤖 xDAN RAG Copilot</h1>
            <p>本地开发环境</p>
            <div id="status" class="status">检查服务状态...</div>
        </div>
        
        <div class="api-test">
            <h2>API测试</h2>
            <button onclick="testHealth()">健康检查</button>
            <button onclick="window.open('/api/docs', '_blank')">查看API文档</button>
            <pre id="result"></pre>
        </div>
    </div>

    <script>
        const API_BASE = 'http://localhost:8050';
        
        async function checkStatus() {
            const statusEl = document.getElementById('status');
            try {
                const response = await fetch(`${API_BASE}/health`);
                const data = await response.json();
                if (data.status === 'ok') {
                    statusEl.className = 'status success';
                    statusEl.textContent = '✅ API服务运行正常';
                } else {
                    throw new Error('服务状态异常');
                }
            } catch (error) {
                statusEl.className = 'status error';
                statusEl.textContent = '❌ API服务连接失败';
            }
        }
        
        async function testHealth() {
            const resultEl = document.getElementById('result');
            try {
                const response = await fetch(`${API_BASE}/health`);
                const data = await response.json();
                resultEl.textContent = JSON.stringify(data, null, 2);
            } catch (error) {
                resultEl.textContent = `错误: ${error.message}`;
            }
        }
        
        // 页面加载时检查状态
        checkStatus();
        // 每5秒检查一次
        setInterval(checkStatus, 5000);
    </script>
</body>
</html>
EOF
        
        # 创建package.json
        cat > "$FRONTEND_DIR/package.json" << EOF
{
  "name": "xdan-rag-frontend",
  "version": "1.0.0",
  "scripts": {
    "dev": "python3 -m http.server $FRONTEND_PORT",
    "serve": "python3 -m http.server $FRONTEND_PORT"
  }
}
EOF
    fi
    
    # 启动前端服务
    cd "$FRONTEND_DIR"
    
    # 检查是否有Node.js项目
    if [ -f "package.json" ] && command -v npm &> /dev/null && [ -f "vite.config.js" -o -f "webpack.config.js" ]; then
        log "INFO" "FRONTEND" "检测到Node.js项目，安装依赖..."
        npm install --silent
        log "INFO" "FRONTEND" "启动前端开发服务器 (端口: $FRONTEND_PORT)"
        nohup npm run dev > "$LOG_DIR/frontend/output_${TIMESTAMP}.log" 2>&1 &
    else
        log "INFO" "FRONTEND" "使用Python HTTP服务器 (端口: $FRONTEND_PORT)"
        nohup python3 -m http.server $FRONTEND_PORT > "$LOG_DIR/frontend/output_${TIMESTAMP}.log" 2>&1 &
    fi
    
    local pid=$!
    echo $pid > "$PID_DIR/frontend.pid"
    
    # 等待服务启动
    sleep 3
    
    # 检查服务
    if kill -0 $pid 2>/dev/null; then
        log "SUCCESS" "FRONTEND" "前端服务启动成功 (PID: $pid)"
        log "INFO" "FRONTEND" "访问地址: http://localhost:$FRONTEND_PORT"
        return 0
    else
        log "ERROR" "FRONTEND" "前端服务启动失败"
        return 1
    fi
}

# 查看日志
tail_logs() {
    local service=$1
    local log_file=$(ls -t "$LOG_DIR/${service}/output_*.log" 2>/dev/null | head -1)
    
    if [ -f "$log_file" ]; then
        log "INFO" "SYSTEM" "查看 $service 日志: $log_file"
        tail -f "$log_file"
    else
        log "ERROR" "SYSTEM" "未找到 $service 日志文件"
    fi
}

# 显示状态
show_status() {
    echo ""
    echo "======================================"
    echo "📊 服务状态"
    echo "======================================"
    
    # 检查后端
    if [ -f "$PID_DIR/backend.pid" ]; then
        local pid=$(cat "$PID_DIR/backend.pid")
        if kill -0 $pid 2>/dev/null; then
            echo "✅ 后端服务: 运行中 (PID: $pid)"
            echo "   地址: http://localhost:$BACKEND_PORT"
            echo "   文档: http://localhost:$BACKEND_PORT/docs"
        else
            echo "❌ 后端服务: 已停止"
        fi
    else
        echo "❌ 后端服务: 未启动"
    fi
    
    # 检查前端
    if [ -f "$PID_DIR/frontend.pid" ]; then
        local pid=$(cat "$PID_DIR/frontend.pid")
        if kill -0 $pid 2>/dev/null; then
            echo "✅ 前端服务: 运行中 (PID: $pid)"
            echo "   地址: http://localhost:$FRONTEND_PORT"
        else
            echo "❌ 前端服务: 已停止"
        fi
    else
        echo "❌ 前端服务: 未启动"
    fi
    
    echo ""
    echo "📁 日志目录: $LOG_DIR"
    echo "======================================"
}

# 主函数
main() {
    case "${1:-start}" in
        start)
            log "INFO" "SYSTEM" "启动 xDAN RAG Copilot 本地服务..."
            
            # 启动后端
            if start_backend; then
                # 启动前端
                if start_frontend; then
                    show_status
                    echo ""
                    log "SUCCESS" "SYSTEM" "所有服务启动成功！"
                    echo ""
                    echo "🎯 快速访问:"
                    echo "   前端应用: http://localhost:$FRONTEND_PORT"
                    echo "   API文档: http://localhost:$BACKEND_PORT/docs"
                    echo "   健康检查: http://localhost:$BACKEND_PORT/health"
                    echo ""
                    echo "📝 管理命令:"
                    echo "   查看状态: $0 status"
                    echo "   停止服务: $0 stop"
                    echo "   重启服务: $0 restart"
                    echo "   查看后端日志: $0 logs backend"
                    echo "   查看前端日志: $0 logs frontend"
                else
                    log "ERROR" "SYSTEM" "前端启动失败"
                fi
            else
                log "ERROR" "SYSTEM" "后端启动失败"
            fi
            ;;
            
        stop)
            log "INFO" "SYSTEM" "停止所有服务..."
            stop_service "backend"
            stop_service "frontend"
            log "SUCCESS" "SYSTEM" "所有服务已停止"
            ;;
            
        restart)
            $0 stop
            sleep 2
            $0 start
            ;;
            
        status)
            show_status
            ;;
            
        logs)
            if [ -z "$2" ]; then
                echo "用法: $0 logs [backend|frontend]"
            else
                tail_logs "$2"
            fi
            ;;
            
        *)
            echo "用法: $0 {start|stop|restart|status|logs}"
            echo ""
            echo "命令说明:"
            echo "  start    - 启动所有服务"
            echo "  stop     - 停止所有服务"
            echo "  restart  - 重启所有服务"
            echo "  status   - 查看服务状态"
            echo "  logs     - 查看服务日志"
            exit 1
            ;;
    esac
}

# 脚本入口
main "$@"