#!/usr/bin/env python3
"""
分析S3架构链路日志
"""
import subprocess
import time

print("S3架构链路日志分析")
print("="*60)
print("请按照以下步骤运行服务并查看日志：")
print()
print("1. 在一个终端中启动服务器：")
print("   python src/api/server.py")
print()
print("2. 在另一个终端中发送测试请求：")
print("   curl -X POST http://localhost:9099/api/v1/chats/{chat_id}/completions \\")
print("   -H 'Content-Type: application/json' \\")
print("   -H 'X-API-Key: your-api-key' \\")
print("   -d '{\"content\": \"智信是什么？\"}'")
print()
print("3. 查看服务器终端中的[S3_TRACE]日志")
print()
print("="*60)
print()
print("日志追踪点：")
print("1. 服务初始化:")
print("   - [S3_TRACE] Starting S3 service initialization...")
print("   - [S3_TRACE] get_default_service called")
print("   - [S3_TRACE] 环境变量状态")
print()
print("2. 请求处理:")
print("   - [S3_TRACE] Chat completion started")
print("   - [S3_TRACE] Checking S3 conditions")
print("   - [S3_TRACE] S3 enhancement conditions met/skipped")
print()
print("3. S3框架处理:")
print("   - [S3_TRACE] enhance_with_s3_framework called")
print("   - [S3_TRACE] Calling s3_service.ask()")
print("   - [S3_TRACE] Received result from s3_service.ask")
print("   - [S3_TRACE] Workflow info found/not found")
print()
print("4. 结果处理:")
print("   - [S3_TRACE] Selected documents数量")
print("   - [S3_TRACE] Search rounds数量")
print("   - [S3_TRACE] S3 result详情")
print()
print("5. 错误处理:")
print("   - [S3_TRACE] Failed to... (各种失败情况)")
print("   - [S3_TRACE] Exception详情和traceback")
print()
print("="*60)
print()
print("调试建议：")
print("1. 如果S3服务没有初始化成功，检查环境变量配置")
print("2. 如果没有进入S3增强流程，检查dataset_ids是否为空")
print("3. 如果没有workflow_info，检查s3_service.ask()的返回值")
print("4. 根据日志中的异常信息定位具体问题")